"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('allow_all', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('connection_errors_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observers_webhook_url'), ['webhook_url'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['observers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    with op.batch_alter_table('observers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observers_webhook_url'))

    op.drop_table('observers')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
