"""registry tables

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('state_detail', sa.String(), nullable=True),
    sa.Column('current_digest', sa.String(), nullable=True),
    sa.Column('previous_digest', sa.String(), nullable=True),
    sa.Column('pending_digest', sa.String(), nullable=True),
    sa.Column('failed_digest', sa.String(), nullable=True),
    sa.Column('approved_resources', sa.JSON(), nullable=True),
    sa.Column('requested_resources', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('last_checked_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=True)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_model_id'), ['model_id'], unique=False)

    op.create_table('resource_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('requested', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_requests_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_requests_model_id'))

    op.drop_table('resource_requests')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_model_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_name'))

    op.drop_table('models')
    # ### end Alembic commands ###
